{
 "title": "Prometheus",
 "panels": [
  {
   "title": "Targets UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "avg(scrape_duration_seconds)" }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}