### create participant
POST http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/participants/invite
Content-Type: application/json

{ 
    "email": "bea@example.com"
}

### get participants
GET http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/participants



### confirm participant
PUT http://localhost:8080/participants/14af0bc9-348c-4def-9c45-ddb11655fc21/confirm
Content-Type: application/json

{ 
    "name": "Beatriz Ribeiro"
}

### remove participant
DELETE http://localhost:8080/participants/0dbcea44-a0d9-457f-85d0-85122371b1b7