### add activity
POST http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/activities
Content-Type: application/json

{ 
    "title": "Visita ao cristo",
    "occursAt": "2024-08-10T00:17:38.686Z"
}

### get activities
GET http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/activities

### delete activity
DELETE http://localhost:8080/activities/62b2e4b1-2f3d-4d73-98a6-91c7665a2bcc




### add link
POST http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/links
Content-Type: application/json

{ 
    "url": "example.com",
    "title": "reserva airbnb"
}

### get links
GET http://localhost:8080/trips/64afd280-fde1-4826-95cb-a05c22134c7b/links

### delete activity
DELETE http://localhost:8080/links/8990be64-e0de-4a27-b730-5900a0043077