CREATE TABLE links ( 
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,

    trip_id UUID NOT NULL,
    FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
)