name: Trivy Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 5" # 1x por semana (sexta-feira 06:00 UTC)
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
          exit-code: 0

      - name: Upload FS scan to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      - name: Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          format: sarif
          output: trivy-config.sarif
          exit-code: 0

      - name: Upload config scan to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-config.sarif
          category: trivy-config